带开关的 “自动代理@启动” & “清除代理@退出” 方案
SeaHOH/GotoX pull request #231
Opened 2022-05-12 03:07 UTC by 1-1-2

增加一个开关，在Windows下使能/禁止以下功能（1启用，0禁用）：
1. 启动时，设置使用自动代理
2. 正常退出时，清除系统代理

2022-05-12 06:13 UTC, SeaHOH requested changes
很好的想法，不过实现有点问题，大概就是上面这些。

2022-05-12 06:13 UTC, SeaHOH commented on launcher/win_tray.py
> +    on_disable_proxy(systray)
这里需要恢复启动前的状态，而不是单纯的清除代理。

在 `enable_proxy(LISTEN_AUTO)` 之前，单独并保存读取以下各项注册表项的有无、类型和值:

    AutoConfigURL, ProxyEnable, ProxyServer, ProxyOverride

然后在这里一一恢复，最后调用：

    Popen((sys.executable, refresh_proxy))

2022-05-12 08:24 UTC, 1-1-2 commented
感谢拔冗回复。也希望跟您聊一聊。

我是从Clash For Windows过来的，它的策略是在软件启动时，保持 软件 上一次的运行状态+覆盖系统代理；退出时，清空系统代理。也是本次修改的灵感来源。

回复中提到的想法很棒——关闭时恢复软件启动前的状态。或许“保留启动前代理状态”也能成为一项新的存储到`dsext.conf`的设置？

另外还有个idea——全局快捷键。比方说通过ctrl+f1~f3实现三种（自动、CFW、禁用）系统代理状态的快速切换。

坦白来说，本能动手就不求人，我尝试理解、魔改了这部分的实现，虽然能在本地运行，但缺乏系统性。

> 如果是从 start.py 启动，则这个功能无法生效。所以不应该将设置放入主配置，而是像事件循环那样放入设置菜单，配置独立或与事件循环配置合并。

我承认我是个代码苦手。这已经超出了我对本项目架构的理解，暂时不具备良好的实现能力。或许还得把这个接力棒交给大佬。

2022-05-12 09:19 UTC, SeaHOH commented
我自己是没有这种需求的，但是要实现自动设置的话，按理就该在退出时恢复原状，否则就可能丢失原配置。当然，退出时也可以根据用户的意愿不恢复，而是设置成其它各种可能的配置。设置存储位置是小事，只要不违反常理，以方便调用为佳，所以这里单独建个文件也不错。

全局快捷键同样，完全可以实现。

如果你对 python 不熟悉，后面的修改可以由我来做。

---

你说得不错，求人不如自己动手，Python 的好处就是上手容易。当初我也是想实践自己的想法才写了这个工具。其实一整个架构挺简陋的，效率也不太行，近几年一直想推倒重来，就是觉得时间不够用。我也是半路出家的野狐禅，缺乏足够的经验，有些流程和架构弄起来就太费时间。

话说为什么想到要用这个工具呢，我估计你应该还在继续使用 Clash 吧？

2022-05-12 09:55 UTC, 1-1-2 commented
主要是为了解决“SNI阻断”这一问题。

反制DNS污染、SNI阻断还能利用CF Workers代理一把梭的，很难有更好的选择了。文档详实，边用边学。

还有一个诱因是，近期出现了预期外的网络波动。

那，这个 PR 可以优雅地close掉了？

2022-05-12 13:25 UTC, 1-1-2 commented
emmm是通过跳过伪造的 RST 包来强行通信吗？有点意思

小搜了以下没有发现，缘分未到。

2022-05-12 13:57 UTC, SeaHOH commented
既然是包过滤，关键字肯定有`packet` `pcap`，再加个 Windows 平台的 pcap 驱动名，还能反污染那加个 `dns`。我试过谷歌和本站都能搜到。
作者写了多个类似工具，只有一个有发布 Windows 预编译文件。先前记错了，其它平台需自行编译。

2022-05-16 04:46 UTC, SeaHOH commented
修改完成，顺便修复和整理了之前有问题的地方，请测试。

另外，快捷键虽然哪里实现都可以，直接在 win_tray.py 中会比较简单，但在这个情景下应该由 winsystray 包提供，那么实现起来就比较麻烦。因为作为一个独立的包，要提供完备的功能才行，必须包含大量快捷键定义或引入新的包。所以当前我并没有添加快捷键。

2022-05-16 11:39 UTC, 1-1-2 commented
运行正常，很棒！

2022-05-16 12:42 UTC, SeaHOH commented on launcher/win_tray.py
> +        ProxyOverride_Current = reg_get_value('ProxyOverride')
干得好！我这么久都发现不了 :smiling_face_with_tear:

2022-05-16 12:43 UTC, SeaHOH requested changes

2022-05-16 12:43 UTC, SeaHOH commented on launcher/win_tray.py
> +        if not ProxyOverride_Current or ProxyOverride_Current == '<local>':
但是这里稍微有点问题。[我查了一下](http://support.microsoft.com/kb/262981)，这个选项中的**本地地址**专指”本地网络中当前所有可用的主机名“，也就是 Windows 中的**计算机名**。所以这个选项的和例外设置是独立的，不应该去掉已存在的 `<local>`，而是把它附加到我们的预设值的最后，既 `预设值;<local>`。

2022-05-16 12:49 UTC, SeaHOH commented on launcher/win_tray.py
> +        ProxyOverride_Current = reg_get_value('ProxyOverride')
不过，这个命名还是可以优化一下。把默认值名称改为 `ProxyOverride_local`，这里就不用改。

2022-05-16 13:11 UTC, SeaHOH requested changes

2022-05-16 13:11 UTC, SeaHOH commented on launcher/win_tray.py
> +        if ProxyOverride == '<local>':
可以用 `elif` 没必要判断两次。

2022-05-16 13:25 UTC, SeaHOH approved these changes

2022-05-16 13:31 UTC, 1-1-2 commented
不客气(●'◡'●)

2022-05-17 14:51 UTC, merged

2022-05-17 15:24 UTC, SeaHOH commented
眼神愈发不行，还是漏了个错误，已单独提交修复。